name: flutter_rte
description: >-
  HTML editor for Flutter (WYSIWYG, rich text) with built-in speech-to-text.

version: 1.0.1

publish_to: none

platforms:
  android:
  ios:
  web:

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flex_color_picker: ^3.7.0
  numberpicker: ^2.1.2
  pointer_interceptor: ^0.10.1
  speech_to_text: ^7.1.0-beta.3
  webview_flutter: ^4.10.0
  meta: ^1.16.0
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - packages/flutter_rte/assets/document.html
    - lib/assets/document.html
